update campaigns set tenant_id = 2 where title = "TIKTOK - KOL BEAUTY - JANUARI 2024 - CANTIKA";
update campaigns set tenant_id = 2 where title = "INSTAGRAM - KOL BEAUTY - JANUARI 2024 - CANTIKA";
update campaigns set tenant_id = 2 where title = "INSTAGRAM - KOL BEAUTY - NADIA - JANUARI 2024";
update campaigns set tenant_id = 2 where title = "TIKTOK - KOL BEAUTY MIKRO - JANUARI 2024 - AISYAH";
update campaigns set tenant_id = 2 where title = "TIKTOK ORGANIK - JANUARI 2024 - TIARA";
update campaigns set tenant_id = 2 where title = "REELS INSTAGRAM - JANUARI 2024";
update campaigns set tenant_id = 2 where title = "INSTAGRAM - KOL BEAUTY - FEBRUARI 2024 - CANTIKA";
update campaigns set tenant_id = 2 where title = "TIKTOK - KOL BEAUTY - FEBRUARI 2024 - CANTIKA";
update campaigns set tenant_id = 2 where title = "INSTAGRAM - KOL BEAUTY - FEBRUARI 2024 - NADIA";
update campaigns set tenant_id = 2 where title = "REELS INSTAGRAM - FEBRUARI 2024";
update campaigns set tenant_id = 2 where title = "TIKTOK ORGANIC - FEBRUARI 2024 - NADILA";
update campaigns set tenant_id = 2 where title = "Instagram Maret 2024 - Nadia";
update campaigns set tenant_id = 2 where title = "TIKTOK - KOL BEAUTY - MARET 2024 - CANTIKA";
update campaigns set tenant_id = 2 where title = "REELS INSTAGRAM ORGANIC - MARET 2024";
update campaigns set tenant_id = 2 where title = "INSTAGRAM - PAID PROMOTE - MARET 2024 - AJENG";
update campaigns set tenant_id = 2 where title = "Tiktok Organic - Maret 2024 - Yayu";
update campaigns set tenant_id = 2 where title = "TIKTOK - KOL BEAUTY - MARET 2024 - NADIA";
update campaigns set tenant_id = 2 where title = "INSTAGRAM - KOL BEAUTY - MARET 2024 - CANTIKA";
update campaigns set tenant_id = 2 where title = "INSTAGRAM BEAUTY APRIL 2024 (NADIA)";
update campaigns set tenant_id = 2 where title = "TIKTOK BEAUTY APRIL 2024 (CANTIKA DAN NADIA)";
update campaigns set tenant_id = 2 where title = "YOUTUBE - APRIL - 2024";
update campaigns set tenant_id = 2 where title = "FEED INSTAGRAM - APRIL - 2024";
update campaigns set tenant_id = 2 where title = "REELS INSTAGRAM - ORGANIC - APRIL 2024";
update campaigns set tenant_id = 2 where title = "TIKTOK ORGANIC - APRIL - 2024";
update campaigns set tenant_id = 2 where title = "NEW KPI TIKTOK KOL MEI 2024";
update campaigns set tenant_id = 2 where title = "INSTAGRAM BEAUTY KOL MEI 2024";
update campaigns set tenant_id = 2 where title = "TIKTOK BEAUTY KOL MEI 2024";
update campaigns set tenant_id = 2 where title = "Tiktok Organic Mei 2024";
update campaigns set tenant_id = 2 where title = "FEED INSTAGRAM - MEI - 2024";
update campaigns set tenant_id = 2 where title = "REELS INSTAGRAM - ORGANIC - MEI 2024";
update campaigns set tenant_id = 2 where title = "NEW KPI TIKTOK KOL JUNI 2024";
update campaigns set tenant_id = 2 where title = "TIKTOK BEAUTY KOL JUNI 2024";
update campaigns set tenant_id = 2 where title = "FEED INSTAGRAM - JUNI - 2024";
update campaigns set tenant_id = 2 where title = "REELS INSTAGRAM - ORGANIC - JUNI 2024";
update campaigns set tenant_id = 2 where title = "Tiktok Organic Juni 2024";
update campaigns set tenant_id = 2 where title = "FEED INSTAGRAM - JULI - 2024";
update campaigns set tenant_id = 2 where title = "REELS INSTAGRAM - ORGANIC - JULI 2024";
update campaigns set tenant_id = 2 where title = "FEED INSTAGRAM - ORGANIC - AGUSTUS 2024";
update campaigns set tenant_id = 2 where title = "REELS INSTAGRAM - ORGANIC - AGUSTUS 2024";
